{"ast":null,"code":"import _regeneratorRuntime from \"/app/node_modules/@babel/runtime/regenerator\";\nimport _asyncToGenerator from \"/app/node_modules/@babel/runtime/helpers/esm/asyncToGenerator\";\nimport { jsxs as _jsxs } from \"react/jsx-runtime\";\nimport { jsx as _jsx } from \"react/jsx-runtime\";\nimport React from 'react';\nimport Layout from '../components/common/Layout';\nimport { useState } from \"react\";\nimport dynamic from \"next/dynamic\";\nimport { logout } from '../components/util/AuthenticationUtil';\n\nvar getErrorCd = function getErrorCd() {\n  return window.location.search.substring(1);\n};\n\nvar Error = function Error() {\n  var _useState = useState(getErrorCd()),\n      errorCd = _useState[0];\n\n  var errorMsg;\n\n  switch (errorCd) {\n    case \"400\":\n      errorMsg = \"不正なリクエストです。\";\n      break;\n\n    case \"401\":\n      errorMsg = \"認証に失敗しました。\";\n      break;\n\n    default:\n      errorMsg = \"エラーが発生しました。\";\n      break;\n  }\n\n  return /*#__PURE__*/_jsxs(Layout, {\n    title: \"Error.\",\n    children: [errorMsg, /*#__PURE__*/_jsx(\"br\", {}), /*#__PURE__*/_jsx(\"br\", {}), /*#__PURE__*/_jsx(\"a\", {\n      onClick: logout,\n      className: \"cursor_pointer\",\n      children: \"\\uFF1C\\uFF1C Back to login page\"\n    })]\n  });\n};\n\nvar DynamicError = dynamic({\n  loader: function () {\n    var _loader = _asyncToGenerator( /*#__PURE__*/_regeneratorRuntime.mark(function _callee() {\n      return _regeneratorRuntime.wrap(function _callee$(_context) {\n        while (1) {\n          switch (_context.prev = _context.next) {\n            case 0:\n              return _context.abrupt(\"return\", Error);\n\n            case 1:\n            case \"end\":\n              return _context.stop();\n          }\n        }\n      }, _callee);\n    }));\n\n    function loader() {\n      return _loader.apply(this, arguments);\n    }\n\n    return loader;\n  }()\n}, {\n  ssr: false\n});\nexport default DynamicError;","map":null,"metadata":{},"sourceType":"module"}